services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    command: sleep infinity
    privileged: true
    expose:
      - 3000
      - 3036
  caddy:
    image: "caddy:2.4.3"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    ports:
      - "3000:3000"
      - "3036:3036"
      - "2379:2379"
      - "9000:9000"
      - "9090:9090"
    depends_on:
      - app
  tidb:
    build:
      context: ./
      dockerfile: Dockerfile.tidb
    volumes:
      - ./tidb/data:/root/.tiup/data
    expose:
      - 2379
      - 3000
      - 4000
      - 9090
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./localstack/boot:/etc/localstack/init/ready.d"
      - "./localstack/data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:
        aliases:
          - sqs.localhost.localstack.cloud
          - s3.localhost.localstack.cloud
          - pictures.s3.localhost.localstack.cloud # S3 bucket for pictures
volumes:
  caddy_config:
